# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  # This option will only trigger a pipeline when changes occur in the result folder
  paths: 
    include:
      - result/*

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cfa0f05b-dcb1-45f5-a57a-e73393aa2f40'
  imageRepository: 'microservices'
  containerRegistry: 'k8votingapp.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool: 
  name: 'azureagent'

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Stage'
    jobs:
      - job: Build
        displayName: 'Build the Image'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: 'Build and push an image to container registry'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

      - job: Push
        displayName: 'Push the Image'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: 'Push the image to container registry'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              command: 'push'
              tags: |
                $(tag)
